name: senan kelly
description: cpssd student in dublin
timezone: Europe/Dublin
permalink: /blog/:title
google_verification: null

sass:
  style: compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Senan Kelly"

exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock

plugins:
    - jekyll-feed
    - jekyll-sitemap
