permalink: /blog/:title

name: senan kelly
description: cpssd student in dublin
timezone: Europe/Dublin
google_verification: null

include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

sass:
  style: compressed
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Senan Kelly"

gems:
  - jekyll-feed
  - jekyll-sitemap
